// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW2JhlUgZ8yHwWz91TLCgyr3DIiSchn_Y',
    appId: '1:1089997613315:android:c8b0d44b1babfbb9532136',
    messagingSenderId: '1089997613315',
    projectId: 'nur-socialmedia-app',
    storageBucket: 'nur-socialmedia-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD07DX4T7XHMLsZpJc9aJl0JcPPR7vX4SY',
    appId: '1:1089997613315:ios:f34413e5e54b67c6532136',
    messagingSenderId: '1089997613315',
    projectId: 'nur-socialmedia-app',
    storageBucket: 'nur-socialmedia-app.appspot.com',
    androidClientId: '1089997613315-5hqfv6h5r86jab0ht1v5m9hmed823186.apps.googleusercontent.com',
    iosClientId: '1089997613315-vuu88ikbuukub1qc4jm198olihrjqvp3.apps.googleusercontent.com',
    iosBundleId: 'com.example.soicalMediaApp',
  );

}